### ISSUE TITLE
favicon upload not working

### ISSUE THREAD

**Issue by Sylensky** [VertisanPRO/Nexus#18]
strangly happens
500x500 pixels, works
![amogus1](https://user-images.githubusercontent.com/71085027/143236299-a87ef178-a446-4b28-b8d5-bd7d276a42fd.jpg)

500x500 pixels, doesnt work
![amogus](https://user-images.githubusercontent.com/71085027/143236343-49b5fa6a-d77d-463a-aa79-93beffecf914.png)

**Comment by PadowYT2** [comment]
got the reason

**Comment by PadowYT2** [comment]
i'll do it when template settings released
