### ISSUE TITLE
Make settings instead of a module

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/Nexus#28]
![image](https://user-images.githubusercontent.com/71085027/140458719-57cd0c34-3cae-448d-a8d7-597f932794c4.png)

**Comment by Sylensky** [comment]
I understand the point that for the user it is more comfortable to have just a settings button right to the template.
But as of the uniqueness aspect i would make it a pseudo settings button. 
For example user clicks the settings button which executes the nexus module installation in background and redirects the user to the nexus module.

**Comment by PadowYT2** [comment]
but why that? if you click the settings u will be promoted with settings and not the module - like defaultrevamp or lithium or others

**Comment by Sylensky** [comment]
You are right. I got a different mindset of how the settings page should look like. If we move the nexus module settings to the template settings the installation process will be a lot easier.

One thing we should keep in mind is we have to create like an importer from nexus module to the template settings.
Once the import is done it deletes the nexus module.

**Comment by PadowYT2** [comment]
oh, i didnt get it in 2 days, now i get it, we can make it easier by telling "do a whole new install of nexus" like others do, and i dont think your option is going to work, because smarty
