### ISSUE TITLE
Exluding Navbar Links

### ISSUE THREAD

**Issue by Sylensky** [VertisanPRO/Nexus#57]
### Is your feature request related to a problem? Please describe

Some links on the navigation bar aren't hideable and would require some changes to navbar.tpl.
For example the status page link location is not configurable and some others aswell.

### Describe the solution you'd like

It would be possible to define a char seperated setting that contains of navlink names that should be excluded.
Then check each navlink item in navbar.tpl if it is inside the setting and if so don't display it.

### Additional context

Futurium for example supports this and it would be a great addition to the settings.

**Comment by PadowYT2** [comment]
Is it really possible? As navbar uses `{forearch}`, it counts as every page

**Comment by Sylensky** [comment]
Yes just check each item if its in the settings list or not and whether it should be displayed.
