### ISSUE TITLE
Getting a "Virus" when downloading!

### ISSUE THREAD

**Issue by Pawwandaa** [VertisanPRO/Nexus#76]
### Describe the issue

I was trying to download the latest nexus file but windows didn't let me it said it wanted to inject the trojan virus or something https://your-mom.is-really-hot.wtf/u/zOOyZYVt

### NamelessMC Version

2.0.0-pr12

### Nexus Version

1.6.1

### To Reproduce

1. Download

### Expected Behaviour

I expect for me to be able to download Nexus and use it

### Desktop

- OS: [Windows 10]
- Browser [OperaGx]

### Screenshots

https://your-mom.is-really-hot.wtf/u/zOOyZYVt

**Comment by ItsLeon15** [comment]
This so called _virus_ does not occur when I download the files.  Make sure to double check where the virus is coming from.

**Comment by PadowYT2** [comment]
What the heck, anyways, .zip cannot be a virus (or like a zip bomb), you can literaly check the source code, also this is Nameless, no idea why is it arguing

**Comment by PadowYT2** [comment]
Also pr12 is not supported

**Comment by Sylensky** [comment]
This is not even related to nexus.
