### ISSUE TITLE
Title page is always "Nexus"

### ISSUE THREAD

**Issue by IkiaeM** [VertisanPRO/Nexus#77]
### Describe the issue

The title of the tab is always "Nexus" on all pages.

### NamelessMC Version

2.0.x

### Nexus Version

1.7.x

### To Reproduce

On all page

### Expected Behaviour

Have the page name

### Desktop

- OS: [e.g. Windows]

### Screenshots

<img width="49" alt="Capture d’écran 2022-08-27 à 13 23 29" src="https://user-images.githubusercontent.com/64362443/187028000-36d97b60-0fb0-41d9-a650-e7ee761ce2d0.png">

### Additional Information

To fix the problem:

Modify in the "Header.tpl" file
Change the variable {$EMBEDTITLE} by {$TITLE}
Line 23 and 54

**Comment by PadowYT2** [comment]
You change it in StaffCP > Layout > Templates > Nexus > Settings > Embed

**Comment by IkiaeM** [comment]
Ah yes ok, it's not ultra clear... I didn't really understand this tab but very well

**Comment by PadowYT2** [comment]
I will point it out I guess, but no idea where
