### ISSUE TITLE
Preloader background color

### ISSUE THREAD

**Issue by IkiaeM** [VertisanPRO/Nexus#78]
### Describe the issue

The color of the preloader is not related to the color mode.

It is always dark even when in light mode.

### NamelessMC Version

2.0.x

### Nexus Version

1.7.x

### To Reproduce

Activate the preloader and change the dark mode, it will always be dark.

### Expected Behaviour

It should be linked to the mode, if it is clear then the preloader is clear, if the mode is dark then it is dark

### Desktop

- OS: [e.g. Windows]

### Screenshots

<img width="1547" alt="Capture d’écran 2022-08-27 à 13 27 47" src="https://user-images.githubusercontent.com/64362443/187028147-e6fa9053-db48-4a73-ba94-f7c92ecdbc34.png">

**Comment by PadowYT2** [comment]
Well I made it dark for everything, but alright, I will make it to a core responding color theme

**Comment by IkiaeM** [comment]
If people really want to be able to change it to something fixed then make an option in the preloader that says "Dynamic", "Light", "Dark"
