### ISSUE TITLE
Activating / deactivating the dark mode does not remove the button at the bottom of the page

### ISSUE THREAD

**Issue by IkiaeM** [VertisanPRO/Nexus#79]
### Describe the issue

Activating / deactivating the dark mode does not remove the button at the bottom of the page

### NamelessMC Version

2.0.x

### Nexus Version

1.7.x

### To Reproduce

Disable the darkmode in the settings and you will always see the button at the bottom of the page

### Expected Behaviour

The button should disappear

### Desktop

- OS: [e.g. Windows]

### Screenshots

<img width="119" alt="Capture d’écran 2022-08-27 à 13 31 49" src="https://user-images.githubusercontent.com/64362443/187028298-60985b96-3d4a-4a2e-91fe-fbd91a598291.png">

**Comment by PadowYT2** [comment]
It is made for Default Mode, like DefaultRevamp has one

**Comment by IkiaeM** [comment]
What is the purpose of the option in Nexus preferences? Because it does not set the default "dark" mode for a new user when it is active. I don't understand the effect of this option...

**Comment by PadowYT2** [comment]
Ah, well it does set, but it somewhy caches it for literally eternity, I will just add a check so it will cache the new option
