### ISSUE TITLE
Nexus Theme & CustomDropDown - Navbar Breaking Completely on Mobile view porting.

### ISSUE THREAD

**Issue by pvpSmashMC** [VertisanPRO/Nexus#89]
### Describe the issue

customdropdown has no options to display dropdown navbar mobile view on the right? it just breaks the navbar itself and moves to the right.

Idk why they get placed that side, throws off the entire view porting on mobile

Then, if you had to use the nice looking navbar dynamic is it ? i cant remember, that NUKES mobile navbars even more with both nexus and dropdown together.

### NamelessMC Version

2.0.x

### Nexus Version

1.7.x

### To Reproduce

1. install nexus
2. click navbar - > style -> modern
3. open phone, view website.
4. navbar breaks completely

1. install nexus
2. click navbar - > style -> any style
3. install customdropdown
4. open phone, view website.
5. navbar icons all break, and move to the right of your screen.

### Expected Behaviour

1. work
2. port-view
3. move icons to left...? on navbar...? why right....??

### Desktop

- OS: [e.g. Windows]

### Screenshots

![unknown](https://user-images.githubusercontent.com/107698480/198027626-f4454db5-a445-4b42-8e70-5f2ecde8ae95.png)

**Comment by PadowYT2** [comment]
Please make 2 issues for 2 problems. Also I won't accept the Modern Navbar error, because you have 0 explanation how does it not work
